# **Final Project**
### Machine Learning Applications

---

**Marta Balairón García 100451724**

**Gracia Estrán Buyo 100452014**

**Marta Almagro Fuello 100451979**


---

## **0. Data set creation**

---

In [ ]:
# Import the necessary libraries:
import pandas as pd
import numpy as np
import pickle
import os
import re
from bs4 import BeautifulSoup

In [ ]:
# Load the Drive helper and mount
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

Mounted at /content/drive

**Function (get_text) that is going to get the text of each chapter of each book:**

In [ ]:
def get_text(text):
    # Find all the matches of 'Capítulo' and their indices:
    matches = re.findall(r'Capítulo \d+', text)
    indices = [m.start() for m in re.finditer(r'Capítulo \d+', text)]

    chapters_index= {}

    # Add the matches and their indices to the dictionary:
    for i in range(len(matches)):
        chapters_index[matches[i]]=indices[i]

    num_chapters = len(chapters_index) #50

    text_array = np.array([])
    matches_array = np.array(matches) #List of chapters (index)
    
    for i, chp in enumerate(matches):

      if i == len(chapters_index)-1: # Case where we get to the final chapter
          index_start = chapters_index[chp]
          text1 = text[index_start:-40]
          #print('---------------------------------Chapter:', chp, 'and text: ', text1)
          clean_text = text1.replace('\n', ' ').replace('\ax0', ' ').replace(chp, ' ')  
          text_array = np.append(text_array, clean_text)


      else:
          index_start = chapters_index[chp]
          chapter2 = matches[i+1]
          index_stop = chapters_index[chapter2] - 1
          text1 = text[index_start:index_stop]
          #print('---------------------------------Chapter:', chp, 'and text: ', text1)
          clean_text = text1.replace('\n', ' ').replace('\ax0', ' ').replace(chp, ' ')  
          text_array = np.append(text_array, clean_text)

    return text_array, matches_array

#print(matches_array[0])
#print('---------------------------------------')
#print(text_array[0])

**Create dataframe of all the chapters from the book of the old testament**

In [ ]:
folder_path_old = '/content/drive/My Drive/AML/Biblia/libros/old' # 43
df_o = pd.DataFrame({'Chapter': [], 'Book': [], 'Testament': [], 'Text': []})

for filename in os.listdir(folder_path_old): 

  with open(folder_path_old + '/' + filename, 'r',  encoding='iso-8859-1') as file:
    soup = BeautifulSoup(file.read(), 'html.parser')
    text = soup.get_text()

    text_array, matches_array = get_text(text)
    test_array = np.full((len(text_array),), "Old")
    book_array = np.full((len(text_array),), filename.rstrip('.html'))

    new_df = pd.DataFrame({'Chapter': matches_array , 'Book': book_array, 'Testament': test_array, 'Text': text_array})
    df_o = pd.concat([df_o, new_df], ignore_index=True)

**Create dataframe of all the chapters from the book of the new testament and join it with the old testament dataframe**

In [ ]:
folder_path_new = '/content/drive/My Drive/AML/Biblia/libros/new' # 27
df_n = pd.DataFrame({'Chapter': [], 'Book': [], 'Testament': [], 'Text': []})

for filename in os.listdir(folder_path_new): 

  with open(folder_path_new + '/' + filename, 'r',  encoding='iso-8859-1') as file:
    soup = BeautifulSoup(file.read(), 'html.parser')
    text = soup.get_text()

    text_array, matches_array = get_text(text)
    test_array = np.full((len(text_array),), "New")
    book_array = np.full((len(text_array),), filename.rstrip('.html'))

    new_df = pd.DataFrame({'Chapter': matches_array , 'Book': book_array, 'Testament': test_array, 'Text': text_array})
    df_n = pd.concat([df_n, new_df], ignore_index=True)

df = pd.concat([df_o, df_n], ignore_index=True) #df.shape[0]=1184

**Save it into a pickle file**

In [ ]:
df.to_pickle('/content/drive/My Drive/AML/Biblia/Dataset.pkl')
#df.to_csv('/content/drive/My Drive/AML/Biblia/Dataset.csv')

In [ ]:
df.head()

,Chapter,Book,Testament,Text
0,Capítulo 1,exodo,Old,Aflicción de los israelitas en Egipto 1:1 Est...
1,Capítulo 2,exodo,Old,Nacimiento de Moisés é2:1 Un varón de la fami...
2,Capítulo 3,exodo,Old,Llamamiento de Moisésé3:1 Apacentando Moisés ...
3,Capítulo 4,exodo,Old,é4:1 Entonces Moisés respondió diciendo: He ...
4,Capítulo 5,exodo,Old,Moisés y Aarón ante Faraón é5:1 Después Moisé...

**The next chunck is to import the database in the notebook**

In [ ]:
with open('/content/drive/My Drive/AML/Biblia/Dataset.pkl', 'rb') as f:
    dataset = pickle.load(f)

**CONTINUE TASKS 1,2 AND 3 IN THE FINALCODE NOTEBOOK**